# Site settings
# Name of your Site
title: University of Manitoba AAPS Student Chapter (UMASC)
email: 

# Short description (goes below the title)
description: University of Manitoba AAPS Student Chapter

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: http://umaaps.github.io
url: http://umaaps.github.io/
projecturl: http://umaaps.github.io/projects/

# Assets URL's
assetsurl: http://umaaps.github.io/assets
imageurl: http://umaaps.github.io/assets/images
bootstrapurl: http://umaaps.github.io/assets/bootstrap

# Build settings
markdown: kramdown

# Social Account
twitter_name: 'UM_AAPS'
twitter_creator: '@UM_AAPS'
twitter_title: University of Manitoba AAPS Student Chapter
twitter_description: University of Manitoba AAPS Student Chapter is the local student chapter of AAPS in Manitoba/Canada.