# Site settings
# Name of your Site
title: University of Manitoba AAPS Student Chapter
email: umaaps.chapter@gmail.com
author: UM_AAPS

# Short description (goes below the title)
description: University of Manitoba AAPS Student Chapter Official Website

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: http://umaaps.github.io
url: http://umaaps.github.io/
projecturl: http://umaaps.github.io/projects/

# Assets URL's
assetsurl: http://umaaps.github.io/assets
imageurl: http://umaaps.github.io/assets/images
bootstrapurl: http://umaaps.github.io/assets/bootstrap
fancyboxurl: http://umaaps.github.io/assets/fancybox
annualactivityurl: http://umaaps.github.io/assets/annualactivity

# Static URL's
staticurl: http://umaaps.github.io/assets

# Build settings
markdown: kramdown

# Social Account
twitter_name: 'UM_AAPS'
twitter_creator: '@UM_AAPS'
twitter_title: University of Manitoba AAPS Student Chapter
twitter_description: University of Manitoba AAPS Student Chapter is the local student chapter of AAPS in Manitoba/Canada.

facebook_page_name: umaapssc

# Your email if you want it to be linked on the contact page
contact_email: umaaps.chapter@gmail.com
web_email: chanyufei@gmail.com

# Committee data
committee_positions: [advisor, chair, vicechair, treasurer]
committee:
  chair:
    name: Sarandeep Malhi
    title: M.Sc.
    gravatar: 05170551876566386559bc24cda5d3ee
    email: malhis@myumanitoba.ca
    position: Chair
  vicechair:
    name: Yufei Chen
    title: Ph.D.
    gravatar: 05170551876566386559bc24cda5d3ee
    email: umche355@myumanitoba.ca
    position: Vice-Chair
  advisor:
    name: Keith Simons
    title: Ph.D.
    gravatar: 05170551876566386559bc24cda5d3ee
    email: Keith.Simons@ad.umanitoba.ca
    position: Faculty Advisor
  secretary:
    name: Yufei Chen
    title: M.Sc.
    gravatar: 05170551876566386559bc24cda5d3ee
    email: umche355@myumanitoba.ca
    position: Secretary
  treasurer:
    name: Sidi Yang
    title: B.Sc.
    gravatar: 05170551876566386559bc24cda5d3ee
    email: sidi.yang@umanitoba.ca
    position: Treasurer

