# Site settings
# Name of your Site
title: UM AAPS Student Chapter
email: 

# Short description (goes below the title)
description: University of Manitoba AAPS Student Chapter

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: http://umaaps.github.io
url: http://umaaps.github.io/
projecturl: http://umaaps.github.io/projects/

# Assets URL's
assetsurl: http://umaaps.github.io/assets
imageurl: http://umaaps.github.io/assets/images/
bootstrapurl: http://umaaps.github.io/assets/bootstrap

# Build settings
markdown: kramdown