# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
baseurl: http://umaaps.github.io
url: http://umaaps.github.io/
projecturl: http://umaaps.github.io/projects/

# Assets URL's
assetsurl: http://umaaps.github.io/assets
imageurl: http://umaaps.github.io/assets/images/
bootstrapurl: http://umaaps.github.io/assets/bootstrap